### PR TITLE
Fix typos for QEMU

### PR DESCRIPTION
**Pull request by afaerber**
Make two text adjustments in the QEMU paragraph in README.md.

### CODE REVIEW

**Comment by afaerber** [comment]
Thanks for selecting QEMU! :smiley:

**Comment by emmairwin** [comment]
Hi @afaerber !  Thanks so much for catching the typo.

The there/their alternation however seems incorrect ('there' is a place, 'their' refers to a person, which in this case we are talking about a person's environment vrs the environment /place).

If that makes sense to you as well, do you mind updating to just have the typo correction?

Thanks very much!

**Comment by bonzini** [comment]
> ('there' is a place, 'their' refers to a person, which in this case we are talking about a person's environment vrs the environment /place

Right, we are talking about "an operating system that is not a person's current environment", i.e. "an operating system that is not __their__ current environment". Using "there" is absolutely wrong.

**Comment by afaerber** [comment]
Hi @emmairwin: Sorry, that was my first time attempting to edit via the GitHub web UI - and me being polite by not criticizing errors in the subject line.
Thought the changes were obvious, but apparently commit messages can never be too verbose. Split into two commits now, with hopefully more clear explanations of both changes.

As Paolo hinted, the explanation is that QEMU allows to run, for example, a Linux VM on a Microsoft Windows system or vice versa. Thus the sentence is referring to the users' (=their) current operating system. Hope it makes sense now?

**Comment by emmairwin** [comment]
Hi @afaerber 
Yes the correct wording is 'their' , I was reversing the diff in my brain, and it's my mistake, but please don't assume bad intentions.
I don't mind criticism, and appreciate feedback.  Thanks for taking the time.  I will merge it.

**Pull request merged**
